[package]
name = "isofs-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
isofs.workspace = true
pretty_env_logger = "0.5.0"
walkdir = "2.5.0"
