[package]
name = "isopod"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "ISO 9660 filesystem library"

[dependencies]
arraystring = "0.3.0"
bitflags = "2.9.4"
bytemuck = "1.23.2"
byteorder = "1.5.0"
log = "0.4.28"
nom = "8.0.0"
thiserror = "2.0.16"
